name: Telegram Notification

on:
  pull_request:
    types: [opened, closed, reopened]
    branches:
      - main
 
jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Send a notification via Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Hello! There was an update in the repository.
            Event Type: ${{ github.event_name }}
            Event Action: ${{ github.event.action }}
            Pull Request Number: ${{ github.event.pull_request.number }}
            Pull Request Title: ${{ github.event.pull_request.title }}
