name: Telegram Notification

on:
  pull_request:
    types: [opened, closed, reopened]
    branches:
      - main

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Send a notification via Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            **🤖Comtrade Backend Review Request!**
            Event Action:${{ github.event.action }}
            PR Title: ${{ github.event.pull_request.title }}
            PR Author: ${{ github.event.pull_request.user.login}}
            PR Link: ${{ github.event.pull_request.html_url }}
