name: Review Submitted

on:
  pull_request_review:
    types:
      - submitted

jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install axios

      - name: Send Telegram notification on PR review approved
        run: node send_telegram_notification.ts
        env:
          TELEGRAM_MESSAGE: "🤖Comtrade Backend PR approved\n\n${{ github.event.review.user.login }} has approved the PR:  ${{ github.event.pull_request.html_url }}"
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}

  commented:
    if: github.event.review.state == 'commented'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install axios

      - name: Send Telegram notification on PR review commented
        run: node send_telegram_notification.ts
        env:
          TELEGRAM_MESSAGE: "🤖Comtrade Backend PR commented!\n\n${{ github.event.review.user.login }} has commented on the PR:   ${{ github.event.pull_request.html_url }}"
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}

  changes:
    if: github.event.review.state == 'changes_requested'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install axios

      - name: Send Telegram notification on PR review changes requested
        run: node send_telegram_notification.ts
        env:
          TELEGRAM_MESSAGE: "🤖Comtrade Backend PR changes requested!!\n\n${{ github.event.review.user.login }} requested changes on the PR:  ${{ github.event.pull_request.html_url }}"
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
