name: Review Submitted

on:
  pull_request_review:
    types:
      - submitted

jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install axios

      - name: Send Telegram Notification
        run: node BootJosephxrex/.github/comtrade-bot/send_notification.ts
        env:
          TELEGRAM_MESSAGE: "<b>🤖Comtrade Backend PR approved</b>${{ github.event.review.user.login }} has approved the PR:  ${{ github.event.pull_request.html_url }}"
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
          TELEGRAM_THREAD_ID: ${{ secrets.TELEGRAM_THREAD_ID }}
          GITHUB_SERVER_URL: ${{ secrets.GITHUB_SERVER_URL }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}

  commented:
    if: github.event.review.state == 'commented'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install axios

      - name: Send Telegram notification on PR review commented
        run: node BootJosephxrex/.github/comtrade-bot/send_notification.ts
        env:
          TELEGRAM_MESSAGE: "<b>🤖Comtrade Backend PR commented!</b><p>${{ github.event.review.user.login }} has commented on the PR:   ${{ github.event.pull_request.html_url }}</p>"
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
          TELEGRAM_THREAD_ID: ${{ secrets.TELEGRAM_THREAD_ID }}
          GITHUB_SERVER_URL: ${{ secrets.GITHUB_SERVER_URL }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}

  changes:
    if: github.event.review.state == 'changes_requested'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install axios

      - name: Send Telegram notification on PR review changes requested
        run: node BootJosephxrex/.github/comtrade-bot/send_notification.ts
        env:
          TELEGRAM_MESSAGE: "<b>🤖Comtrade Backend PR changes requested!!</b><p>${{ github.event.review.user.login }} requested changes on the PR:  ${{ github.event.pull_request.html_url }}<p>"
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
          TELEGRAM_THREAD_ID: ${{ secrets.TELEGRAM_THREAD_ID }}
          GITHUB_SERVER_URL: ${{ secrets.GITHUB_SERVER_URL }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
