name: Review Submitted

on:
  pull_request_review:
    types:
      - submitted

jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github/comtrade-bot
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Send Telegram Notification on PR merged
        run: npm start
        env:
          ACTION: APPROVED
          REVIEW_USER: ${{ github.event.review.user.login }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
          TELEGRAM_THREAD_ID: ${{ secrets.TELEGRAM_THREAD_ID }}
          REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME }}

  commented:
    if: github.event.review.state == 'commented'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github/comtrade-bot
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Send Telegram Notification on PR merged
        run: npm start
        env:
          ACTION: COMMENTED
          REVIEW_USER: ${{ github.event.review.user.login }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
          TELEGRAM_THREAD_ID: ${{ secrets.TELEGRAM_THREAD_ID }}
          REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME }}

  changes:
    if: github.event.review.state == 'changes_requested'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github/comtrade-bot
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Send Telegram Notification on PR merged
        run: npm start
        env:
          ACTION: CHANGES
          REVIEW_USER: ${{ github.event.review.user.login }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
          TELEGRAM_THREAD_ID: ${{ secrets.TELEGRAM_THREAD_ID }}
          REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME }}
