name: Notify on PR submitted reviews

on:
  pull_request_review:
    types:
      - submitted

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram notification on PR review submitted
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            <b>🤖Comtrade Backend PR Reviewed!</b>

            ${{ github.event.review.user.login }} has reviewed the PR ${{ github.event.pull_request.title }}
          format: html
